version: "3.9"

services:
  rinha-api1:
    image: weibemoura/rinha-app:latest
    container_name: rinha-api1
    hostname: rinha-api1
    environment:
      - DATABASE_URL=jdbc:postgresql://rinha-pg:5432/rinha-db
      - DATABASE_USERNAME=rinha
      - DATABASE_PASSWORD=rinha@123
    depends_on:
      rinha-pg:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '960MB'
    networks:
      - net
    healthcheck:
#      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/ || exit 1
      test: echo 0 || exit 1
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 5s

  rinha-api2:
    image: weibemoura/rinha-app:latest
    container_name: rinha-api2
    hostname: rinha-api2
    environment:
      - DATABASE_URL=jdbc:postgresql://rinha-pg:5432/rinha-db
      - DATABASE_USERNAME=rinha
      - DATABASE_PASSWORD=rinha@123
    depends_on:
      rinha-pg:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '960MB'
    networks:
      - net
    healthcheck:
#      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/ || exit 1
      test: echo 0 || exit 1
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 5s

  rinha-nginx:
    image: nginx:latest
    container_name: rinha-nginx
    volumes:
      - $PWD/contrib/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      rinha-api1:
        condition: service_healthy
      rinha-api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '128MB'

  rinha-pg:
    image: postgres:15
    container_name: rinha-pg
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/pgdata:rw
      - $PWD/contrib/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha@123
      - POSTGRES_DB=rinha-db
      - PGDATA=/pgdata
    command: "postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1GB'
    networks:
      - net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha -d rinha-db" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  postgresql:
    driver: local

networks:
  net:
    driver: bridge