POST http://127.0.0.1:8080/pessoas HTTP/1.1
Content-Type: application/json

{
    "apelido" : "josé",
    "nome" : "José Roberto",
    "nascimento" : "2000-10-01",
    "stack" : ["C#", "Node", "Oracle"]
}

###

GET http://127.0.0.1:8080/pessoas/34d5f8f7-b472-4a74-846a-d13a139043c5 HTTP/1.1
Accept: application/json

###

GET http://127.0.0.1:8080/pessoas?t=moura HTTP/1.1
Accept: application/json

###

GET http://127.0.0.1:8080/contagem-pessoas HTTP/1.1
Accept: application/json